services:
  ai:
    build:
      context: .
      dockerfile: AI/Dockerfile
    container_name: AI_BACKEND
    image: ai_backend:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
    env_file:
      - .env.ai
    command: npx ts-node index.ts
